In [1]:
from __future__ import annotations

import os
from typing import Any

import pandas as pd
import psycopg
from psycopg.rows import dict_row

DEFAULT_URL = "postgresql://weave:weave@localhost:5432/weave"

In [2]:
def read_df(sql: str, params: Any = None) -> pd.DataFrame:
    """Run a SQL query and return a DataFrame. params is a psycopg argument tuple/dict."""
    url = os.environ.get("DATABASE_URL") or DEFAULT_URL
    with psycopg.connect(url, row_factory=dict_row) as conn:
        rows = conn.execute(sql, params).fetchall()
    return pd.DataFrame(rows)

In [3]:
import sys
from pathlib import Path

root = Path.cwd()
if not (root / "scripts" / "pg.py").exists():
    root = root.parent
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

from scripts.pg import read_df
from IPython.display import display

tables = read_df("""
    SELECT table_name, table_type
    FROM information_schema.tables
    WHERE table_schema = 'public'
    ORDER BY table_type, table_name
""")
display(tables)

     table_name  table_type
0    fetch_meta  BASE TABLE
1  issue_labels  BASE TABLE
2        issues  BASE TABLE
3   org_members  BASE TABLE
4     pr_labels  BASE TABLE
5           prs  BASE TABLE
6       reviews  BASE TABLE
7         users  BASE TABLE
8     pr_volume        VIEW
9  review_reach        VIEW

In [4]:
prs_df = read_df("select * from prs")

prs_df.head()

,number,title,body,state,comments,created_at,closed_at,updated_at,html_url,author_login,author_type
0,59792,feat(web-analytics): add lazy precompute rollo...,## Problem\n\nThe lazy precompute path (PR #59...,closed,3,2026-05-23 18:32:09+00:00,2026-05-23 21:35:59+00:00,2026-05-23 21:36:01+00:00,https://github.com/PostHog/posthog/pull/59792,lricoy,User
1,59787,fix(insights): allow viewed/timing/metalytics ...,## Problem\n\nCloses a fresh `ReadOnlyModeErro...,closed,4,2026-05-23 15:23:49+00:00,2026-05-23 18:00:38+00:00,2026-05-23 18:34:21+00:00,https://github.com/PostHog/posthog/pull/59787,posthog[bot],Bot
2,59784,fix(llma): route personal_spend through events...,## Problem\n\n`/api/llm_analytics/@me/spend/` ...,closed,5,2026-05-23 15:15:57+00:00,2026-05-23 18:31:54+00:00,2026-05-23 20:08:09+00:00,https://github.com/PostHog/posthog/pull/59784,pauldambra,User
3,59781,chore(insights): move retention bar/line chart...,## Problem\n\nContinues the migration started ...,closed,4,2026-05-23 14:41:52+00:00,2026-05-23 15:39:13+00:00,2026-05-23 18:34:20+00:00,https://github.com/PostHog/posthog/pull/59781,sampennington,User
4,59779,test: fix reverseProxyCheckerLogic read-only t...,## Summary\n\n`frontend/src/lib/components/Rev...,closed,4,2026-05-23 12:18:53+00:00,2026-05-23 12:47:03+00:00,2026-05-23 14:31:46+00:00,https://github.com/PostHog/posthog/pull/59779,arnohillen,User

In [5]:
prs_df.comments.describe()

count    13476.000000
mean         5.232191
std          3.081051
min          0.000000
25%          3.000000
50%          5.000000
75%          6.000000
max         96.000000
Name: comments, dtype: float64

In [6]:
prs_df.dtypes

number                            int64
title                               str
body                                str
state                               str
comments                          int64
created_at      datetime64[us, Etc/UTC]
closed_at       datetime64[us, Etc/UTC]
updated_at      datetime64[us, Etc/UTC]
html_url                            str
author_login                        str
author_type                         str
dtype: object

In [7]:
prs_df.author_type.value_counts()

author_type
User    12533
Bot       943
Name: count, dtype: int64

In [8]:
prs_df[prs_df.author_type == "Bot"]["author_login"].value_counts()

author_login
posthog[bot]                      548
mendral-app[bot]                  166
scheduled-actions-posthog[bot]    112
posthog-js-upgrader[bot]           93
inkeep[bot]                        10
tests-posthog[bot]                  7
dependabot[bot]                     5
clickhouse-sync-posthog[bot]        2
Name: count, dtype: int64

In [9]:
prs_df[prs_df.author_type != "Bot"].author_login.value_counts().head(25)

author_login
Gilbert09          2214
pauldambra          517
andrewm4894         356
sampennington       344
rnegron             286
webjunkie           237
skoob13             217
MattPua             212
jonmcwest           209
tatoalo             204
arthurdedeus        175
thmsobrmlr          172
lricoy              166
sakce               166
arnohillen          163
danielcarletti      157
rafaeelaudibert     155
jurajmajerik        148
VojtechBartos       141
DanielVisca         140
robbie-c            136
haacked             132
hpouillot           129
ksvat               126
jose-sequeira       122
Name: count, dtype: int64

In [10]:
issues_df = read_df("select * from issues")

issues_df.head()

,number,title,body,state,comments,created_at,closed_at,updated_at,html_url,author_login,author_type
0,59707,Bug report :`$ai_evaluation` Custom analytics ...,### Issue\n\n# PostHog: `$ai_evaluation` Custo...,closed,0,2026-05-22 18:09:12+00:00,2026-05-22 18:14:22+00:00,2026-05-22 18:14:22+00:00,https://github.com/PostHog/posthog/issues/59707,alauxui,User
1,59492,test,test,closed,0,2026-05-21 18:35:48+00:00,2026-05-21 18:36:03+00:00,2026-05-21 18:36:03+00:00,https://github.com/PostHog/posthog/issues/59492,posthog[bot],Bot
2,59344,Allow custom day labeling in retention cohort ...,Context/ Problem:\n\nPostHog currently labels ...,closed,1,2026-05-21 08:24:22+00:00,2026-05-22 09:08:33+00:00,2026-05-22 09:08:34+00:00,https://github.com/PostHog/posthog/issues/59344,hait0ng,User
3,59036,ProseMirror-selectednode CSS class is added to...,### Bug Description\n\n## How to reproduce\n\n...,closed,1,2026-05-19 15:07:18+00:00,2026-05-21 14:34:38+00:00,2026-05-21 14:34:38+00:00,https://github.com/PostHog/posthog/issues/59036,crash-and-burn,User
4,57019,Account tagging and segmentation,- Automatic account segmentation: when a certa...,closed,0,2026-04-29 20:33:37+00:00,2026-05-21 23:37:12+00:00,2026-06-09 18:13:31+00:00,https://github.com/PostHog/posthog/issues/57019,arthurdedeus,User

In [11]:
users_df = read_df("select * from users")

users_df.head()

,login,name,company,type,bio,avatar_url,html_url,merged_pr_count,is_public_member,is_affiliated
0,Gilbert09,Tom Owers,NaN,User,,https://avatars.githubusercontent.com/u/145926...,https://github.com/Gilbert09,2214,True,True
1,pauldambra,Paul D'Ambra,@posthog,User,,https://avatars.githubusercontent.com/u/984817...,https://github.com/pauldambra,517,True,True
2,andrewm4894,Andrew Maguire,PostHog,User,AI Product Engineer @ PostHog working on LLM A...,https://avatars.githubusercontent.com/u/217829...,https://github.com/andrewm4894,356,True,True
3,sampennington,Sam Pennington,VEED,User,,https://avatars.githubusercontent.com/u/560245...,https://github.com/sampennington,344,False,False
4,rnegron,Raúl Negrón-Otero,@PostHog,User,"puertorriqueño, senior software developer, upr...",https://avatars.githubusercontent.com/u/415310...,https://github.com/rnegron,286,True,True

In [12]:
res = (
prs_df[prs_df.author_type != "Bot"].author_login.value_counts().head(50).reset_index()
    .merge(users_df[["login", "name", "company"]], left_on="author_login", right_on="login", how="left")
)

display(res)

,author_login,count,login,name,company
0,Gilbert09,2214,Gilbert09,Tom Owers,NaN
1,pauldambra,517,pauldambra,Paul D'Ambra,@posthog
2,andrewm4894,356,andrewm4894,Andrew Maguire,PostHog
3,sampennington,344,sampennington,Sam Pennington,VEED
4,rnegron,286,rnegron,Raúl Negrón-Otero,@PostHog
5,webjunkie,237,webjunkie,Julian Bez,@PostHog
6,skoob13,217,skoob13,Georgiy Tarasov,PostHog
7,MattPua,212,MattPua,Matt Pua,PostHog
8,jonmcwest,209,jonmcwest,Jon McCallum,@PostHog
9,tatoalo,204,tatoalo,Alessandro Pogliaghi,@posthog
10,arthurdedeus,175,arthurdedeus,Arthur Moreira de Deus,@posthog
11,thmsobrmlr,172,thmsobrmlr,Thomas Obermüller,PostHog
12,lricoy,166,lricoy,Lucas Ricoy,@PostHog
13,sakce,166,sakce,Jovan Sakovic,@PostHog
14,arnohillen,163,arnohillen,Arno Hillen,NaN
15,danielcarletti,157,danielcarletti,Daniel RC,NaN
16,rafaeelaudibert,155,rafaeelaudibert,Rafael Audibert,@posthog
17,jurajmajerik,148,jurajmajerik,Juraj Majerik,NaN
18,VojtechBartos,141,VojtechBartos,Vojta Bartoš,@Posthog
19,DanielVisca,140,DanielVisca,Daniel Visca,"@PostHog, ex-Microsoft"
20,robbie-c,136,robbie-c,Robbie,@posthog
21,haacked,132,haacked,Phil Haack,Haacked LLC
22,hpouillot,129,hpouillot,Hugues Pouillot,NaN
23,ksvat,126,ksvat,Kim Svatos Dugan,NaN
24,jose-sequeira,122,jose-sequeira,José Sequeira,NaN
25,TueHaulund,119,TueHaulund,Tue Haulund,NaN
26,fercgomes,115,fercgomes,Fernando Gomes,Posthog
27,eli-r-ph,114,eli-r-ph,Eli Reisman,https://github.com/PostHog
28,dmarchuk,111,dmarchuk,Daniel Marchuk,@PostHog
29,Radu-Raicea,109,Radu-Raicea,Radu Raicea,@PostHog
30,mayteio,109,mayteio,Harley Alexander,NaN
31,z0br0wn,109,z0br0wn,Zach Brown,NaN
32,luke-belton,109,luke-belton,Luke Belton,PostHog
33,andehen,107,andehen,Anders,ex @oda
34,Piccirello,106,Piccirello,Tom Piccirello,PostHog
35,veryayskiy,106,veryayskiy,Alex V,NaN
36,joshsny,105,joshsny,Joshua Snyder,PostHog
37,gantoine,105,gantoine,Georges-Antoine Assi,@posthog
38,cat-ph,104,cat-ph,Catalin,NaN
39,jabahamondes,101,jabahamondes,Javier Bahamondes,NaN
40,carlos-marchal-ph,98,carlos-marchal-ph,Carlos Marchal,NaN
41,estefaniarabadan,96,estefaniarabadan,estefania,NaN
42,mp-hog,94,mp-hog,Marcel Poelker,NaN
43,thiagosalvatore,94,thiagosalvatore,Thiago Salvatore,PostHog
44,ablaszkiewicz,93,ablaszkiewicz,Aleksander Błaszkiewicz,PostHog
45,meikelmosby,92,meikelmosby,Meikel Ratz,NaN
46,frankh,90,frankh,Frank Hamand,NaN
47,Twixes,87,Twixes,Michael Matloka,@PostHog
48,vdekrijger,85,vdekrijger,Vasco de Krijger,@PostHog
49,EDsCODE,84,EDsCODE,Eric Duong,Posthog

In [13]:
users_df.company.value_counts()

company
PostHog                                    34
@PostHog                                   22
@PostHog                                   19
@posthog                                    6
Posthog                                     4
VEED                                        1
@posthog                                    1
@Posthog                                    1
@PostHog, ex-Microsoft                      1
Haacked LLC                                 1
https://github.com/PostHog                  1
ex @oda                                     1
Posthog | Manager of bits                   1
42 Ducks                                    1
permapeople.org                             1
University of Cambridge                     1
Posthog, Inc                                1
@CarletonComputerScienceSociety             1
Vendia                                      1
Nirma university                            1
trunk-io                                    1
@ciaoelsa                                   1
@movedot (YC F25)                           1
@adjust                                     1
RASG Digital                                1
CloudQuery                                  1
@WeesWares                                  1
Oracle                                      1
@pixiebrix                                  1
@simpleclub                                 1
SharafDG                                    1
Higher school of communication of Tunis     1
Name: count, dtype: int64

In [14]:
reviews_df = read_df("select * from reviews")

reviews_df.sample(5)

      reviewer_login  pr_number
9988       Gilbert09      69349
7831   georgemunyoro      66088
10493      hpouillot      78604
1244         rnegron      61391
9741       Gilbert09      71309

In [15]:
issue_labels_df = read_df("select * from issue_labels")

issue_labels_df["label"].value_counts().head(50)

label
enhancement                   321
bug                           219
team/product-analytics         80
team/feature-flags             75
feature/customer-analytics     70
team/data-warehouse            53
feature/feature-flags          52
feature/pipeline-sources       46
feature/desktop                43
feature/libraries              32
feature/replay                 30
team/experiments               23
feature/dashboards             20
team/analytics-platform        20
feature/cohorts                17
feature/mobile                 15
feature/insights               15
feature/funnels                13
good first issue               11
feature/workflows              10
feature/trends                 10
team/session-replay            10
team/platform-features         10
sprint                          9
team/conversations              9
team/workflows                  8
team/web-analytics              8
feature/conversations           8
team/self-driving               8
feature/error-tracking          7
team/error-tracking             7
feature/mcp                     7
team/posthog-ai                 7
feature/surveys                 7
feature/signals                 7
ui-ux-improvement               6
security                        6
team/surveys                    6
feature/actions                 5
ux                              5
feature/posthog-ai              5
team/mcp-analytics              5
feature/data-warehouse          5
team/ai-observability           5
feature/mcp-analytics           5
feature/messaging               4
feature/pipelines               4
feature/property-filters        4
team-devex                      4
team/llm-analytics              4
Name: count, dtype: int64

In [16]:
display(read_df("select * from review_reach").sort_values("reviewed_others", ascending=False).head(25))

     reviewer_login  reviewed_others  distinct_authors
53         MarconLP              583                15
32         gantoine              489                77
35        Gilbert09              437                57
6       andrewm4894              344                41
72          rnegron              271                50
81          skoob13              267                44
68  rafaeelaudibert              253                47
92        webjunkie              210                43
84          tatoalo              182                32
63       pauldambra              179                43
49           lricoy              172                32
54      mariusandra              170                42
31       fuziontech              168                 9
67      Radu-Raicea              168                26
15           cat-ph              163                12
44          joshsny              151                23
37        hpouillot              148                22
23         dmarchuk              148                18
2     ablaszkiewicz              144                16
71   richardsolomou              136                30
33    georgemunyoro              133                32
60      nickbest-ph              133                11
65       Piccirello              132                47
56          MattPua              123                37
9      arthurdedeus              122                25

In [17]:
display(read_df("select * from pr_labels"))
read_df("select * from pr_labels").label.value_counts().head(25)

      pr_number              label
0         59792           stamphog
1         59787           stamphog
2         59781           stamphog
3         59766           stamphog
4         59754           stamphog
...         ...                ...
7573      71730              stale
7574      71730  skip-agent-review
7575      69889           stamphog
7576      69889    run-ci-frontend
7577      66355          reviewhog

[7578 rows x 2 columns]

label
stamphog                      4333
skip-agent-review              583
reviewhog                      527
skip-inkeep-docs               365
feature/desktop                326
team/feature-flags             248
feature/feature-flags          166
run-ci-frontend                130
stale                          118
automated                      114
feature/cohorts                 81
trunk-merge-queue-submit        69
update-snapshots                50
graphite-merge-queue            44
waiting                         44
llm-analytics                   40
run-ci-backend                  37
priority-review                 24
automerge                       24
skip-desktop-backend-check      22
bug                             19
no-snapshot-update              19
docs                            15
team/llm-analytics              14
team/product-analytics          12
Name: count, dtype: int64

In [18]:
pr_labels_df = read_df("select * from pr_labels")

pr_labels_df.label.value_counts().head(25)

label
stamphog                      4333
skip-agent-review              583
reviewhog                      527
skip-inkeep-docs               365
feature/desktop                326
team/feature-flags             248
feature/feature-flags          166
run-ci-frontend                130
stale                          118
automated                      114
feature/cohorts                 81
trunk-merge-queue-submit        69
update-snapshots                50
graphite-merge-queue            44
waiting                         44
llm-analytics                   40
run-ci-backend                  37
priority-review                 24
automerge                       24
skip-desktop-backend-check      22
bug                             19
no-snapshot-update              19
docs                            15
team/llm-analytics              14
team/product-analytics          12
Name: count, dtype: int64

In [19]:
!pip install openrouter dotenv

Collecting openrouter
  Using cached openrouter-1.1.74-py3-none-any.whl.metadata (11 kB)
Collecting dotenv
  Using cached dotenv-0.9.9-py2.py3-none-any.whl.metadata (279 bytes)
Requirement already satisfied: httpcore>=1.0.9 in /Users/bethanybaker/Desktop/weave-takehome/.venv/lib/python3.14/site-packages (from openrouter) (1.0.9)
Requirement already satisfied: httpx>=0.28.1 in /Users/bethanybaker/Desktop/weave-takehome/.venv/lib/python3.14/site-packages (from openrouter) (0.28.1)
Collecting jsonpath-python>=1.0.6 (from openrouter)
  Using cached jsonpath_python-1.1.6-py3-none-any.whl.metadata (17 kB)
Collecting pydantic<2.13,>=2.11.2 (from openrouter)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting annotated-types>=0.6.0 (from pydantic<2.13,>=2.11.2->openrouter)
  Using cached annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<2.13,>=2.11.2->openrouter)
  Using cached pydantic_core-2.41.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (7.3 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/bethanybaker/Desktop/weave-takehome/.venv/lib/python3.14/site-packages (from pydantic<2.13,>=2.11.2->openrouter) (4.16.0)
Collecting typing-inspection>=0.4.2 (from pydantic<2.13,>=2.11.2->openrouter)
  Using cached typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting python-dotenv (from dotenv)
  Using cached python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: certifi in /Users/bethanybaker/Desktop/weave-takehome/.venv/lib/python3.14/site-packages (from httpcore>=1.0.9->openrouter) (2026.7.22)
Requirement already satisfied: h11>=0.16 in /Users/bethanybaker/Desktop/weave-takehome/.venv/lib/python3.14/site-packages (from httpcore>=1.0.9->openrouter) (0.16.0)
Requirement already satisfied: anyio in /Users/bethanybaker/Desktop/weave-takehome/.venv/lib/python3.14/site-packages (from httpx>=0.28.1->openrouter) (4.14.2)
Requirement already satisfied: idna in /Users/bethanybaker/Desktop/weave-takehome/.venv/lib/python3.14/site-packages (from httpx>=0.28.1->openrouter) (3.19)
Using cached openrouter-1.1.74-py3-none-any.whl (925 kB)
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Using cached pydantic_core-2.41.5-cp314-cp314-macosx_11_0_arm64.whl (1.9 MB)
Using cached dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Using cached annotated_types-0.8.0-py3-none-any.whl (13 kB)
Using cached jsonpath_python-1.1.6-py3-none-any.whl (14 kB)
Using cached typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Using cached python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Installing collected packages: typing-inspection, python-dotenv, pydantic-core, jsonpath-python, annotated-types, pydantic, dotenv, openrouter
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [openrouter] 7/8 [openrouter]
Successfully installed annotated-types-0.8.0 dotenv-0.9.9 jsonpath-python-1.1.6 openrouter-1.1.74 pydantic-2.12.5 pydantic-core-2.41.5 python-dotenv-1.2.3 typing-inspection-0.4.4

In [20]:
from openrouter import OpenRouter
import os
from dotenv import load_dotenv
 
load_dotenv()

True

In [21]:
prs_df.head()

,number,title,body,state,comments,created_at,closed_at,updated_at,html_url,author_login,author_type
0,59792,feat(web-analytics): add lazy precompute rollo...,## Problem\n\nThe lazy precompute path (PR #59...,closed,3,2026-05-23 18:32:09+00:00,2026-05-23 21:35:59+00:00,2026-05-23 21:36:01+00:00,https://github.com/PostHog/posthog/pull/59792,lricoy,User
1,59787,fix(insights): allow viewed/timing/metalytics ...,## Problem\n\nCloses a fresh `ReadOnlyModeErro...,closed,4,2026-05-23 15:23:49+00:00,2026-05-23 18:00:38+00:00,2026-05-23 18:34:21+00:00,https://github.com/PostHog/posthog/pull/59787,posthog[bot],Bot
2,59784,fix(llma): route personal_spend through events...,## Problem\n\n`/api/llm_analytics/@me/spend/` ...,closed,5,2026-05-23 15:15:57+00:00,2026-05-23 18:31:54+00:00,2026-05-23 20:08:09+00:00,https://github.com/PostHog/posthog/pull/59784,pauldambra,User
3,59781,chore(insights): move retention bar/line chart...,## Problem\n\nContinues the migration started ...,closed,4,2026-05-23 14:41:52+00:00,2026-05-23 15:39:13+00:00,2026-05-23 18:34:20+00:00,https://github.com/PostHog/posthog/pull/59781,sampennington,User
4,59779,test: fix reverseProxyCheckerLogic read-only t...,## Summary\n\n`frontend/src/lib/components/Rev...,closed,4,2026-05-23 12:18:53+00:00,2026-05-23 12:47:03+00:00,2026-05-23 14:31:46+00:00,https://github.com/PostHog/posthog/pull/59779,arnohillen,User

In [22]:
user_pr_df = prs_df[prs_df.author_type != "Bot"].copy()[["title", "body", "state", "comments", "author_login"]]
user_pr_df.head()

,title,body,state,comments,author_login
0,feat(web-analytics): add lazy precompute rollo...,## Problem\n\nThe lazy precompute path (PR #59...,closed,3,lricoy
2,fix(llma): route personal_spend through events...,## Problem\n\n`/api/llm_analytics/@me/spend/` ...,closed,5,pauldambra
3,chore(insights): move retention bar/line chart...,## Problem\n\nContinues the migration started ...,closed,4,sampennington
4,test: fix reverseProxyCheckerLogic read-only t...,## Summary\n\n`frontend/src/lib/components/Rev...,closed,4,arnohillen
5,chore(mcp): reuse master schema cache to skip ...,## Problem\n\nMCP integration tests were runni...,closed,2,joshsny

In [23]:
import re

COMMIT = re.compile(r"^(?P<type>\w+)(?:\((?P<scope>[^)]+)\))?\s*:\s*(?P<subject>.+)$", re.I)

def parse_pr_title(title: str) -> pd.Series:
    m = COMMIT.match((title or "").strip())
    if not m:
        return pd.Series({"commit_type": "other", "scope": None, "subject": title})
    return pd.Series({
        "commit_type": m.group("type").lower(),
        "scope": (m.group("scope") or "").lower() or None,
        "subject": m.group("subject").strip(),
    })

prs = read_df("SELECT number, title, author_login FROM prs")
parsed = prs.join(prs["title"].apply(parse_pr_title))
parsed.head()

,number,title,author_login,commit_type,scope,subject
0,59792,feat(web-analytics): add lazy precompute rollo...,lricoy,feat,web-analytics,add lazy precompute rollout metrics
1,59787,fix(insights): allow viewed/timing/metalytics ...,posthog[bot],fix,insights,allow viewed/timing/metalytics telemetry POSTs...
2,59784,fix(llma): route personal_spend through events...,pauldambra,fix,llma,route personal_spend through events table to d...
3,59781,chore(insights): move retention bar/line chart...,sampennington,chore,insights,move retention bar/line charts into product_an...
4,59779,test: fix reverseProxyCheckerLogic read-only t...,arnohillen,test,NaN,fix reverseProxyCheckerLogic read-only test af...

In [24]:
parsed[parsed.scope.isna()].commit_type.value_counts()

commit_type
chore       144
fix         115
feat        105
ci           21
docs         11
revert       11
refactor      9
other         9
test          4
perf          1
Name: count, dtype: int64

In [25]:
parsed.scope.value_counts().head(25)

scope
data-warehouse        1569
signals                456
ci                     369
experiments            343
tasks                  332
insights               321
replay-vision          299
llma                   293
flags                  245
error-tracking         243
logs                   236
mcp                    234
data-imports           221
desktop                220
workflows              212
web-analytics          202
replay                 192
aio                    177
customer-analytics     166
postgres               159
hogql                  158
dashboards             155
conversations          149
cdp                    141
mcp-analytics          133
Name: count, dtype: int64

In [26]:
parsed.groupby(["author_login", "commit_type"]).size().unstack(fill_value=0).sort_values("feat", ascending=False).head(10)

commit_type,chore,ci,docs,feat,fix,other,perf,refactor,revert,test
author_login,,,,,,,,,,
Gilbert09,39,0,1,954,1210,0,1,6,1,2
andrewm4894,58,0,0,218,74,0,0,4,2,0
pauldambra,98,1,3,169,176,0,13,45,2,10
jonmcwest,9,0,1,151,46,0,0,2,0,0
sampennington,59,0,0,136,134,0,1,14,0,0
arthurdedeus,1,0,0,132,29,0,1,11,1,0
MattPua,28,0,2,118,55,0,1,7,1,0
skoob13,32,0,0,104,72,0,2,3,4,0
DanielVisca,12,0,1,89,37,0,1,0,0,0
lricoy,14,0,1,84,55,0,10,1,0,1

In [27]:
BRACKET = re.compile(r"^\[([^\]]+)\]", re.I)
BUG = re.compile(r"^bug report", re.I)

def classify_issue_title(title: str) -> pd.Series:
    t = (title or "").strip()
    low = t.lower()

    m = COMMIT.match(t)
    if m:
        return pd.Series({"issue_kind": "conventional", "tag": m.group("type").lower(), "scope": m.group("scope")})

    m = BRACKET.match(t)
    if m:
        return pd.Series({"issue_kind": "bracket", "tag": m.group(1).strip(), "scope": None})

    if BUG.match(low):
        return pd.Series({"issue_kind": "bug_report", "tag": "bug", "scope": None})
    if "feature request" in low:
        return pd.Series({"issue_kind": "feature_request", "tag": "feature", "scope": None})
    if "?" in t:
        return pd.Series({"issue_kind": "question", "tag": "question", "scope": None})

    return pd.Series({"issue_kind": "freeform", "tag": None, "scope": None})

issues = read_df("SELECT number, title, author_login FROM issues")
issues = issues.join(issues["title"].apply(classify_issue_title))
issues["issue_kind"].value_counts()

issue_kind
freeform           586
conventional       187
feature_request    120
bug_report          41
bracket             31
question             4
Name: count, dtype: int64

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

freeform = issues.loc[issues["issue_kind"] == "freeform", "title"].tolist()
X = TfidfVectorizer(max_features=500, stop_words="english").fit_transform(freeform)
labels = KMeans(n_clusters=8, random_state=0, n_init="auto").fit_predict(X)

for k in range(8):
    print(f"\n--- cluster {k} ---")
    for t in [freeform[i] for i, lab in enumerate(labels) if lab == k][:5]:
        print(" ", t[:90])

--- cluster 0 ---
  ProseMirror-selectednode CSS class is added to all images in dashboards
  Renaming an action doesn't take effect until after a refresh.
  Nuxt error tracking docs use deprecated/incorrect `sourcemaps.project` key
  Sprint - May 4 to May 17
  Move `scheduled_at` out of workflow trigger

--- cluster 1 ---
  Handover notes for customer accounts
  Data migration to customer analytics
  Group analytics mega-issue
  Connect persons to accounts
  Add Device Make/Model for insights/web analytics

--- cluster 2 ---
  test
  Flaky test quarantined: tools/hogli-commands/hogli_commands/tests/test_test_runner.py
  Stabilize the multimodal trace Playwright test
  test
  SDK Compliance Test Harness Status

--- cluster 3 ---
  Add coupon data from Stripe to Stripe source
  GitHub warehouse source: deployment_statuses can never sync (PostHog GitHub App lacks depl
  Repeat source map uploads fail with Symbol set already has a release ID
  Logs “Related errors” tab fails with illegal_division when volumeResolution is 0
  Surface signal source health (enablement) for Inbox

--- cluster 4 ---
  Switching Posthog tabs on the Create New Feature Flag page clears any unsaved details
  Experiment creation persist flag across auth steps should follow project preference
  Cross-project feature flag copy: MCP tool non-functional + missing skill
  Update SDK local evaluation for per-condition-set aggregation
  Date picker: LemonUI vs Quill feature parity audit

--- cluster 5 ---
  @posthog/cli ships outdated shrinkwrapped transitive deps with open CVEs (axios, follow-re
  Add support for retention / stickiness as experiment metric
  bug[MCP]: claude.ai connector fails with 'Tool exec not found' on PostHog MCP
  posthog-react-native eagerly imports react-native-svg (declared optional) from main entryp
  Lost dashboard /insight view when switch to AI posthog

--- cluster 6 ---
  Allow custom day labeling in retention cohort charts (e.g., start from D1 instead of D0)
  Account tagging and segmentation
  Account Billing and Usage tab
  Instrument dashboard-widget custom-view → feature-enable conversion
  Save custom accounts table views

--- cluster 7 ---
  Add a "wait for event" action to workflows
  Add day of the week to trends graph summary overlay
  Add `$session_id` to all client libraries
  Add library version into headers of integrations
  Add `page` function to all libraries